/**
 * API request/response types, hand-written now against @bannersin48/shared.
 * When M1 (backend) ships openapi.json, this file is regenerated by openapi-typescript
 * and downstream consumers do not change.
 */

import type {
  Address,
  AddressValidationResult,
  ArtworkUploadMeta,
  DeliveryResponse,
  Finishing,
  Material,
  Order,
  OrderStatus,
  PricingInput,
  PricingLine,
  RegisterInput,
  LoginInput,
  User,
} from "@bannersin48/shared";

export interface ApiClientConfig {
  baseUrl: string;
  /**
   * Inject the current auth token. In the browser this reads from a cookie via
   * the Next.js Route Handler proxy, so the value is null in client code and
   * the httpOnly cookie carries auth automatically.
   */
  getToken?: () => string | null;
  fetchImpl?: typeof fetch;
}

export interface QuoteResponse {
  lines: PricingLine[];
  subtotal: number;
  shipping: number;
  total: number;
  eligible: boolean;
  guaranteedDeliveryDate: string;
  guaranteedDeliveryDow: string;
  cutoffInMs: number;
  cutoffAtEt: string;
}

export interface ArtworkUploadResponse {
  artworkId: string;
  previewUrl: string;
  meta: ArtworkUploadMeta;
}

export interface OrderListItem {
  id: string;
  orderNumber: string;
  status: OrderStatus;
  total: number;
  totalLabel: string;
  createdAt: string;
  firstLineLabel: string;
  firstLineQty: number;
  guaranteedDeliveryDate: string;
}

export interface CreateOrderInput {
  email: string;
  lines: Array<{
    material: Material;
    dimensions: PricingInput["dimensions"];
    finishing: Finishing;
    quantity: number;
    artworkId?: string;
  }>;
  shipTo?: Address;
  shipToUnverified?: boolean;
  paymentMethod: "stub_card" | "stub_paypal" | "stub_apple_pay";
}

export interface ApproveProofInput {
  acknowledgements: {
    artworkCorrect: boolean;
    spellingColorsLayoutAccepted: boolean;
    printsAsUploaded: boolean;
    cancellationWindowUnderstood: boolean;
    deliveryDateAndAddressConfirmed: boolean;
  };
}

export interface ApiError {
  code: string;
  message: string;
  details?: Record<string, unknown>;
}

export type {
  Address,
  AddressValidationResult,
  DeliveryResponse,
  Material,
  Order,
  OrderStatus,
  User,
  RegisterInput,
  LoginInput,
};
