/**
 * API request/response types, hand-written now against @bannersin48/shared.
 * When M1 (backend) ships openapi.json, this file is regenerated by openapi-typescript
 * and downstream consumers do not change.
 */

import type {
  Address,
  AddressValidationResult,
  ArtworkUploadMeta,
  DeliveryResponse,
  Finishing,
  ForgotPasswordInput,
  Material,
  Order,
  OrderStatus,
  PaymentStatus,
  PricingInput,
  PricingLine,
  RegisterInput,
  LoginInput,
  ResetPasswordInput,
  User,
} from "@bannersin48/shared";

export interface ApiClientConfig {
  baseUrl: string;
  /**
   * Inject the current auth token. In the browser this reads from a cookie via
   * the Next.js Route Handler proxy, so the value is null in client code and
   * the httpOnly cookie carries auth automatically.
   */
  getToken?: () => string | null;
  fetchImpl?: typeof fetch;
}

export interface QuoteResponse {
  quoteId: string;
  validUntil: string;
  currency: "USD";
  lines: PricingLine[];
  subtotal: number;
  shipping: number;
  tax: number;
  total: number;
  eligible: boolean;
  guaranteedDeliveryDate: string;
  guaranteedDeliveryDow: string;
  cutoffInMs: number;
  cutoffAtEt: string;
}

export interface BannerCatalogCard {
  id: string;
  slug: string;
  title: string;
  subtitle: string;
  hasMoreInfo: boolean;
  route: string;
}

export interface BannerCatalogInfo {
  id: string;
  slug: string;
  title: string;
  subtitle: string;
  commonUses: string[];
  environment: string[];
  options: string[];
}

export interface ArtworkUploadResponse {
  artworkId: string;
  previewUrl: string;
  meta: ArtworkUploadMeta;
}

export interface OrderListItem {
  id: string;
  orderNumber: string;
  status: OrderStatus;
  paymentStatus: PaymentStatus;
  total: number;
  totalLabel: string;
  createdAt: string;
  placedAt: string | null;
  firstLineLabel: string;
  firstLineQty: number;
  guaranteedDeliveryDate: string;
}

export interface CreateOrderInput {
  email: string;
  lines: Array<{
    productId?: string;
    material: Material;
    dimensions: PricingInput["dimensions"];
    finishing: Finishing;
    quantity: number;
    artworkId: string;
    quoteId: string;
  }>;
  shipTo: Address;
  addressValidationToken: string;
  addressRiskAcknowledged: boolean;
  acknowledgements: OrderAcknowledgements;
}

export interface ReorderResponse {
  sourceOrderId: string;
  lines: Array<{
    sourceOrderLineId: string;
    productId: string;
    material: Material;
    dimensions: PricingInput["dimensions"];
    finishing: Finishing;
    quantity: number;
    artworkId: string;
    quote: QuoteResponse;
  }>;
  warnings: string[];
}

export interface OrderAcknowledgements {
  artworkCorrect: boolean;
  spellingColorsLayoutAccepted: boolean;
  printsAsUploaded: boolean;
  cancellationWindowUnderstood: boolean;
  deliveryDateAndAddressConfirmed: boolean;
}

export interface ApiError {
  code: string;
  message: string;
  details?: Record<string, unknown>;
}

export type {
  Address,
  AddressValidationResult,
  DeliveryResponse,
  ForgotPasswordInput,
  Material,
  Order,
  OrderStatus,
  PaymentStatus,
  RegisterInput,
  LoginInput,
  ResetPasswordInput,
  User,
};
